version: '3.6'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v14.9.1
    container_name: gitlab-runner
    privileged: true
    volumes:
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: "256m"