version: '3.6'
services:
  web:
    # ce为社区版，ee为企业版
    image: gitlab/gitlab-ce:14.9.1-ce.0
    container_name: gitlab-server
    # 指定主机地址，如果有域名可以指向域名（一般我们指定为gitlab所在服务器的公网IP，以便外部访问）
    hostname: "192.168.100.68"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.100.68:8929'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.163.com'
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = 'yourmail@163.com'
        gitlab_rails['smtp_password'] = 'YCDOMZHSUJTVKZWW'
        gitlab_rails['smtp_domain'] = '163.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'yourmail@163.com'
        gitlab_rails['gitlab_email_display_name'] = 'My Gitlab'
        user['git_user_email'] = 'yourmail@163.com'
    ports:
      - "8929:8929"
      - "2224:22"
    volumes:
      # windows需要修改.为对应的目录名如：D:\
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: "256m"
